baseURL = "https://nitishspatkar.github.io/blog.itubi/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "yinyang"
[params]
headTitle = "itubi blog"
mainSections = ["posts"]
[[params.socials]]
name = "Follow me on LinkedIn"
link = "https://www.linkedin.com/in/nitishpatkar/"


